### ISSUE TITLE
Replace modal system in branch "wip/John/auth-modal" by the <dialog> element.

### ISSUE THREAD

**Issue by joaoiacillo** [Fultonium-Entertainment/website#4]
Hey guys! Long time no see. I came to drop a quick enhancement for the website! When I was working in the project I made a totally custom modal system in JS, but what I didn't know back then was that the browsers already have a modal dialog system built-in.

When you got the time to look on it, read the [MDN docs](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog) about it. It's waaaaaayyy simpler than the junk I made! 😂

Miss you all.

**Comment by LeCodingWolfie** [comment]
> browsers already have a modal dialog system built-in.

Huh, I didn't knew about it until now. Otherwise, I would be writing websites with code written like that, or worse :laughing:. Anyways, thanks for the update, will check this while working back on the website :D

**Comment by joaoiacillo** [comment]
Will be implemented in the future for other issue.
